[package]
name = "polyfuse-example-hello"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
polyfuse = { path = "../../crates/polyfuse" }

libc = "0.2"
pico-args = "0.5"
tracing = "0.1"
tracing-subscriber = "0.3"
