[package]
name = "polyfuse-xtask"
version = "0.0.0" # never publish
publish = false
edition = "2018"

[dependencies]
anyhow = "1"
json = "0.12"
once_cell = "1"
pico-args = "0.3"
regex = "1.4"
wait-timeout = "0.2"
